---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(rio)
library(sf)
library(stars)
library(raster)
library(terra)
```


```{r}
sal <- import("01_datos/Conductividad_electrica.csv")
```

```{r}
head(sal)
```

```{r}
raster_list <- list.files(path = "01_datos/prueba", full.names = TRUE)
```

```{r}
raster_list
```


```{r}
rasters <- read_stars(raster_list)
```


```{r}
rasters <- st_transform(rasters, crs = 5367)
```

```{r}
rasters
```


```{r}
cr <- st_read("01_datos/mask/CR_crtm05.gpkg")
```
```{r}
st_crs(cr)
```


```{r}
plot(cr["AREA"], axes = TRUE)
```

```{r}
plot(rasters, axes = TRUE)
```


```{r}
rasters_mask <- rasters[cr, crop = TRUE]
```


```{r}
plot(rasters_mask, axes = TRUE)
```


```{r}
r <- read_stars("01_datos/covs/B02CHE3.tif")
```



```{r}
plot(r)
```

### terra

```{r}
raster_list <- list.files(path = "01_datos/prueba", full.names = TRUE)
```

```{r}
s <- stack(raster_list)
```

```{r}
s
```

```{r}
crs = "+proj=tmerc +lat_0=0 +lon_0=-84 +k=0.9999 +x_0=500000 +y_0=0 +ellps=WGS84 +units=m +no_defs"
s <- projectRaster(s, crs = crs)   
```


```{r}
s_crop <- crop(s, cr)
```

```{r}
s_mask <- mask(s_crop, cr)
```


