---
title: "Untitled"
output: html_document
---

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(rio)
library(sf)
library(stars)
library(rgdal)
library(raster)
library(rasterVis)
library(terra)
library(randomForest)
library(ranger)
library(caret)
library(DALEX)
library(ingredients)
library(auditor)
library(colorDF)
```


```{r}
ce <- import("03_variables_modelos/ce_df.xlsx")
```

```{r}
ce <- dplyr::select(ce, ce, C04MCF5, OCSTHA_M_sd6_1km_ll, TAXNWRB_Fibric.Histosols_1km_ll, M06MOD4, TAXNWRB_Plinthic.Acrisols_1km_ll)
```

```{r}
ce %>% colorDF
```

```{r}
cr_cg <- shapefile("01_datos/mask/Cr_wgs84_meso.shp")
```


```{r}
rasters_list <- list.files(path = "03_variables_modelos/rasters", full.names = TRUE)
```


```{r}
rasters_list
```

```{r}
rasters <- stack(rasters_list)
```


```{r}
plot(rasters)
```

```{r}
s_crop <- crop(rasters, cr_cg)
```


```{r}
s_mask <- mask(s_crop, cr_cg)
```

```{r}
s_mask
```

```{r}
set.seed(100)
rf_01 <- randomForest(ce ~ ., data = ce, importance = TRUE)
```

```{r}
library(parameters)
lm_01 <- lm(ce ~ ., data = ce)
```

```{r}
model_parameters(lm_01) %>% colorDF
```


```{r}
rf_01
```

```{r}
e_lm <- explain(lm_01, data = ce[, -1], y = ce$ce, label = "lm")
e_rf <- explain(rf_01, data = ce[, -1], y = ce$ce, label = "rf")
```

```{r}
mp_lm <- DALEX::model_performance(e_lm)
mp_rf <- DALEX::model_performance(e_rf)
```

```{r}
plot(mp_lm, mp_rf, geom = "boxplot")
```

```{r}
mp_lm
```


```{r}
mp_rf
```


```{r}
rf_map <- predict(s_mask, rf_01)
```


```{r}
rf_map
```

```{r}
plot(rf_map)
```

```{r}
rf_map_stars <- st_as_stars(rf_map)
```


```{r}
ggplot() +
  geom_stars(data = rf_map_stars) +
  coord_equal() +
  theme_minimal() +
  scale_fill_viridis_c(name = "ce", option = "A", na.value = "transparent", direction = -1)
```

```{r}
ggsave("mapa_ce.png", height = 8, width = 10)
```



```{r}
e_rf <- explain(rf_01, data = ce[, -1], y = ce$ce, label = "rf")
```

```{r}
mp_rf <- model_performance(e_rf)
```

```{r}
mp_rf
```

```{r}
fi_rp <- feature_importance(e_rf)
```

```{r}
plot(fi_rp, show_boxplots = FALSE)
```

```{r}
pd_rf <- partial_dependence(e_rf)
```

```{r}
plot(pd_rf)
```


```{r}
dem1 <- raster("dem/DEM1/med30crtm05_No_Sinks.tif")
```

```{r}
plot(dem1)
```









