---
title: "Preparación de los datos"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(rio)
library(sf)
library(stars)
library(sp)
library(raster)
library(rasterVis)
library(terra)
library(SDMtune)
library(sdmpredictors)
library(ENMTools)
library(caret)
library(mapview)
```


```{r}
sal <- import("01_datos/Conductividad_electrica.csv")
```

```{r}
head(sal)
```
```{r}
sal_sf <- st_as_sf(sal,
                   coords = c("x", "y"),
                   crs = 5367)
```

```{r}
mapview(sal_sf)
```


```{r}
st_write(sal_sf, "01_datos/sal.shp")
```

```{r}
sal <- st_read("01_datos/sal.shp")
```

```{r}
sal_cg <- st_transform(sal, crs = 4326)
```


```{r}
st_write(sal_cg, "01_datos/sal_cg.shp")
```
```{r}
mapview(sal)
```

```{r}
sal_vect <- vect("01_datos/sal.shp")
```

```{r}
crs <- "+proj=longlat +datum=WGS84 +no_defs"
```

```{r}
cr_vect <- vect("01_datos/mask/CR_cg.gpkg")
```

```{r}
sal_vect_cg <- project(sal_vect, cr_vect)
```

```{r}
sal_vect_cg
```


***

### terra (raster)

```{r}
cr_terra_crtm05 <- vect("01_datos/mask/CR_crtm05.gpkg")
cr_terra_cg <- vect("01_datos/mask/CR_cg.gpkg")
```

```{r}
cr <- shapefile("01_datos/mask/Costa_Rica_CRTM05.shp")
crs(cr)
```

```{r}
rasters_list <- list.files(path = "01_datos/covs_todas", full.names = TRUE)
```


```{r}
s <- rast(rasters_list)
```

```{r}
s
```

```{r}
s_crop <- crop(s, cr_terra_cg)
```


```{r}
s_mask <- mask(s_crop, cr_terra_cg)
```


```{r}
s_mask
```

```{r}
variables <- extract(s_mask, sal_sp_cg)
```



```{r}
raster.cor.matrix(s_mask)
```


***

### stars


```{r}
r1 <- read_stars("01_datos/rasters_cat/C01MCF5.tif")
r2 <- read_stars("01_datos/rasters_cat/C02MCF5.tif")
r3 <- read_stars("01_datos/rasters_cat/C03MCF5.tif")
r4 <- read_stars("01_datos/rasters_cat/C04MCF5.tif")
r5 <- read_stars("01_datos/rasters_cat/C05MCF5.tif")
r6 <- read_stars("01_datos/rasters_cat/C06MCF5.tif")
r7 <- read_stars("01_datos/rasters_cat/C07MCF5.tif")
r8 <- read_stars("01_datos/rasters_cat/C08MCF5.tif")
r9 <- read_stars("01_datos/rasters_cat/C09MCF5.tif")
r10 <- read_stars("01_datos/rasters_cat/C10MCF5.tif")
r11 <- read_stars("01_datos/rasters_cat/C11MCF5.tif")
r12 <- read_stars("01_datos/rasters_cat/C12MCF5.tif")
```


```{r}
r1$cont = 1.0 * as.numeric(r1[[1]])
r2$cont = 1.0 * as.numeric(r2[[1]])
r3$cont = 1.0 * as.numeric(r3[[1]])
r4$cont = 1.0 * as.numeric(r4[[1]])
r5$cont = 1.0 * as.numeric(r5[[1]])
r6$cont = 1.0 * as.numeric(r6[[1]])
r7$cont = 1.0 * as.numeric(r7[[1]])
r8$cont = 1.0 * as.numeric(r8[[1]])
r9$cont = 1.0 * as.numeric(r9[[1]])
r10$cont = 1.0 * as.numeric(r10[[1]])
r11$cont = 1.0 * as.numeric(r11[[1]])
r12$cont = 1.0 * as.numeric(r12[[1]])
```

```{r}
write_stars(r1["cont"], "01_datos/covs_todas/C01MCF5.tif")
write_stars(r2["cont"], "01_datos/covs_todas/C02MCF5.tif")
write_stars(r3["cont"], "01_datos/covs_todas/C03MCF5.tif")
write_stars(r4["cont"], "01_datos/covs_todas/C04MCF5.tif")
write_stars(r5["cont"], "01_datos/covs_todas/C05MCF5.tif")
write_stars(r6["cont"], "01_datos/covs_todas/C06MCF5.tif")
write_stars(r7["cont"], "01_datos/covs_todas/C07MCF5.tif")
write_stars(r8["cont"], "01_datos/covs_todas/C08MCF5.tif")
write_stars(r9["cont"], "01_datos/covs_todas/C09MCF5.tif")
write_stars(r10["cont"], "01_datos/covs_todas/C10MCF5.tif")
write_stars(r11["cont"], "01_datos/covs_todas/C11MCF5.tif")
write_stars(r12["cont"], "01_datos/covs_todas/C12MCF5.tif")
```


```{r}
rasters_list <- list.files(path = "01_datos/covs_todas", full.names = TRUE)
```

```{r}
rasters <- read_stars(rasters_list)
```

```{r}
cr_stars <- st_read("01_datos/mask/CR_cg.gpkg")
```

```{r}
plot(cr_stars)
```


```{r}
rasters_mask <- rasters[cr_stars]
```

```{r}
write_stars(rasters_mask, "02_rasters/rasters_mask.tif")
```

```{r}
rasters_p <- st_transform(rasters_mask, crs = 5367)
```

```{r}
st_crs(rasters_p)
```

```{r}
plot(rasters_p, axes = TRUE)
```

```{r}
names(rasters_p)
```


```{r}
r001 <- rasters_p[48]
```

```{r}
plot(r001)
```


```{r}
ggplot() + geom_stars(data = r001) +
    coord_equal() +
    theme_void() +
    scale_x_discrete(expand=c(0,0))+
    scale_y_discrete(expand=c(0,0))
```


***

### Extracción de variables

```{r}
sal_sf <- st_as_sf(sal,
                   coords = c("x", "y"),
                   crs = 5367)
```


```{r}
sal_sf_cg <- st_transform(sal_sf, crs = 4326)
```

```{r}
plot(sal_sf_cg)
```


```{r}
st_crs(sal_sf_cg)
```

```{r}
variables <- st_extract(rasters_mask, sal_sf_cg)
```

```{r}
variables
```

```{r}
variables %>% st_as_sf()
```

### raster

```{r}
sal_cg <- shapefile("01_datos/sal_cg.shp")
```

```{r}
sal_cg@coords
```

```{r}
rasters_list <- list.files(path = "01_datos/covs_todas", full.names = TRUE)
```

```{r}
s <- stack(rasters_list)
```

```{r}
s
```

```{r}
variables <- extract(s, sal_cg, df = TRUE)
```

```{r}
summary(variables)
```


### caret

```{r}
ctrl <- rfeControl(functions = lmFuncs,
                   method = "repeatedcv",
                   repeats = 5,
                   verbose = FALSE)
```


```{r}
lmProfile <- rfe(x, y,
                 sizes = subsets,
                 rfeControl = ctrl)
```




