---
title: "Mapa de salinidad"
output: html_document
---

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(rio)
library(sf)
library(stars)
library(rgdal)
library(raster)
library(rasterVis)
library(terra)
library(randomForest)
library(ranger)
library(caret)
library(DALEX)
library(ingredients)
library(auditor)
library(colorDF)
library(CAST)
library(landmap)
library(mlr)
library(mapview)
library(patchwork)
```


```{r}
ce <- import("03_variables_modelos/ce_df.xlsx")
```


```{r}
ce <- dplyr::select(ce, ce, C04MCF5, OCSTHA_M_sd6_1km_ll, TAXNWRB_Fibric.Histosols_1km_ll, M06MOD4, TAXNWRB_Plinthic.Acrisols_1km_ll)
```

```{r}
head(ce)
```

```{r}
ce_sp <- import("03_variables_modelos/ce_sp.xlsx")
```

```{r}
head(ce_sp)
```

```{r}
coordinates(ce_sp) <- ~x+y
```

```{r}
proj4string(ce_sp) <- CRS("+init=epsg:5367")
```

```{r}
ce_sp <- spTransform(ce_sp, CRS("+proj=longlat +datum=WGS84"))
```

```{r}
ce_sp
```

```{r}
cr_cg_sf <- st_read("01_datos/mask/CR_cg.gpkg")
```

```{r}
cr_cg_sp <- as(cr_cg_sf, "Spatial")
```


```{r}
r_cr_mask <- raster("01_datos/mask/mask.tif")
```

```{r}
plot(r_cr_mask)
```


```{r}
rasters_list_salinidad <- list.files(path = "03_variables_modelos/rasters", full.names = TRUE)
```


```{r}
rasters_list_salinidad
```

```{r}
rasters_para_salinidad <- stack(rasters_list_salinidad)
```


```{r}
plot(rasters_para_salinidad)
```


```{r}
stack_salinidad <- as(rasters_para_salinidad, "SpatialPixelsDataFrame")
```

```{r}
landmap_salinidad <- train.spLearner(ce_sp["ce"], covariates = stack_salinidad[ , c("C04MCF5", "OCSTHA_M_sd6_1km_ll", "TAXNWRB_Fibric.Histosols_1km_ll", "M06MOD4", "TAXNWRB_Plinthic.Acrisols_1km_ll")], lambda = 1)
```

```{r}
summary(landmap_salinidad@spModel$learner.model$super.model$learner.model)
```


```{r}
landmap_salinidad
```

```{r}
landmap_salinidad_p <- predict(landmap_salinidad)
```

```{r}
mapa_salinidad <- raster(landmap_salinidad_p$pred["response"])
```

```{r}
plot(mapa_salinidad)
```


```{r}
mapa_salinidad_masked <- mask(mapa_salinidad, r_cr_mask)
```

```{r}
writeRaster(mapa_salinidad_masked, file = "rasters_salinidad/mapa_salinidad_masked.tif", overwrite = TRUE)
```

```{r}
plot(mapa_salinidad_masked)
```

```{r}
mapa_salinidad_error <- raster(landmap_salinidad_p$pred["model.error"])
```


```{r}
mapa_salinidad_error_masked <- mask(mapa_salinidad_error, r_cr_mask)
```

```{r}
writeRaster(mapa_salinidad_error_masked, file = "rasters_salinidad/mapa_salinidad_error_masked.tif", overwrite = TRUE)
```


```{r}
plot(mapa_salinidad_error_masked)
```


```{r}
plot(raster(landmap_salinidad_p$pred["response"]), axes = TRUE, box = FALSE)
```

```{r}
mapview(raster(landmap_salinidad_p$pred["response"]))
```


```{r}
plot(raster(landmap_salinidad_p$pred["model.error"]), 
   main = "Model error", axes = FALSE, box = FALSE)
```

```{r, include=FALSE}
m1 <- gplot(mapa_salinidad_masked) +
  theme_minimal() +
  geom_tile(aes(fill = value)) +
  scale_fill_viridis_c(name = "CE", na.value = "transparent") +
  coord_equal()
```

```{r, include=FALSE}
m2 <- gplot(mapa_salinidad_error_masked) +
  theme_minimal() +
  geom_tile(aes(fill = value)) +
  scale_fill_viridis_c(name = "Error del \nmodelo", na.value = "transparent") +
  coord_equal()
```


```{r}
m1 + m2
```

```{r}
ggsave("mapas_salinidad/mapas_salinidad.png")
```





```{r}
```



```{r}
set.seed(100)
rf_01 <- randomForest(ce ~ ., data = ce, importance = TRUE)
```

```{r}
library(parameters)
lm_01 <- lm(ce ~ ., data = ce)
```

```{r}
model_parameters(lm_01) %>% colorDF
```


```{r}
rf_01
```

```{r}
e_lm <- explain(lm_01, data = ce[, -1], y = ce$ce, label = "lm")
e_rf <- explain(rf_01, data = ce[, -1], y = ce$ce, label = "rf")
```

```{r}
mp_lm <- DALEX::model_performance(e_lm)
mp_rf <- DALEX::model_performance(e_rf)
```

```{r}
plot(mp_lm, mp_rf, geom = "boxplot")
```

```{r}
mp_lm
```


```{r}
mp_rf
```


```{r}
rf_map <- predict(s_mask, rf_01)
```


```{r}
rf_map
```

```{r}
plot(rf_map)
```

```{r}
rf_map_stars <- st_as_stars(rf_map)
```


```{r}
ggplot() +
  geom_stars(data = rf_map_stars) +
  coord_equal() +
  theme_minimal() +
  scale_fill_viridis_c(name = "ce", option = "A", na.value = "transparent", direction = -1)
```

```{r}
ggsave("mapa_ce.png", height = 8, width = 10)
```



```{r}
e_rf <- explain(rf_01, data = ce[, -1], y = ce$ce, label = "rf")
```

```{r}
mp_rf <- model_performance(e_rf)
```

```{r}
mp_rf
```

```{r}
fi_rp <- feature_importance(e_rf)
```

```{r}
plot(fi_rp, show_boxplots = FALSE)
```

```{r}
pd_rf <- partial_dependence(e_rf)
```

```{r}
plot(pd_rf)
```


```{r}
dem1 <- raster("dem/DEM1/med30crtm05_No_Sinks.tif")
```

```{r}
plot(dem1)
```









